import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import About from "@/components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title> Luc | Développeur full-stack </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Projects />
      <Contact />
    </div>
  );
}